version: '3.4'

services:
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports: 
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: identity
      MYSQL_USER: identity
      MYSQL_PASSWORD: identity
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
    ports:
      - "7000:7000"
    depends_on:
      - mysql
    links:
      - mysql
  mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7006
    ports:
      - "7006:7006"
    links:
      - identity

volumes:
  db_data:
